"""
Policy Comparison Analysis Script

This script analyzes and visualizes the performance of different charging policies
by comparing key metrics across multiple simulations.

Comparison Metrics:
    1. Charging Time: Total time to reach 100% SoC
    2. Temperature Profile: Peak, average, and time-dependent temperature
    3. SEI Growth: Final SEI thickness and degradation rate
    4. Efficiency: Energy input vs. useful charging energy

Output:
    - comparison_policies.png: Multi-panel comparison plot
    - policy_metrics_summary.csv: Detailed metrics table (generated by main.py)
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import glob
import os
from datetime import datetime

# ==============================
# CONFIGURATION
# ==============================
LOG_DIR = "log"
METRICS_FILE = f"{LOG_DIR}/policy_metrics_summary.csv"

# ==============================
# LOAD METRICS
# ==============================
if not os.path.exists(METRICS_FILE):
    print(f"Metrics file not found: {METRICS_FILE}")
    print("Please run main.py first to generate simulation data.")
    exit(1)

metrics_df = pd.read_csv(METRICS_FILE)
print(f"Loaded metrics for {len(metrics_df)} policies:")
print(metrics_df.to_string(index=False))

# ==============================
# LOAD CYCLE DATA FOR FIRST CYCLE
# ==============================
policy_data = {}
for idx, row in metrics_df.iterrows():
    policy_name = row['Policy']
    
    # Find the first cycle file for this policy
    pattern = f"{LOG_DIR}/log_{policy_name}_cycle1.csv"
    files = glob.glob(pattern)
    
    if files:
        df = pd.read_csv(files[0])
        policy_data[policy_name] = df
        print(f"Loaded {policy_name}: {len(df)} data points")
    else:
        print(f"Warning: Could not find cycle1 file for {policy_name}")

# ==============================
# CREATE OPTIMIZED 2x2 COMPARISON PLOT
# ==============================
plt.style.use("seaborn-v0_8-darkgrid")
fig = plt.figure(figsize=(14, 10))
gs = fig.add_gridspec(2, 2, hspace=0.35, wspace=0.3)

# Extract data
policies = metrics_df['Policy'].values
times_hours = metrics_df['Charging_Time_Hours'].values
times_min = times_hours * 60  # Convert to minutes
peak_temps = metrics_df['Peak_Temp_K'].values
sei_growth = metrics_df['SEI_Growth'].values

# Base color palette
colors_base = plt.cm.Set3(np.linspace(0, 1, len(policies)))

# ========================
# PANEL 1: Charging Time Comparison
# ========================
ax1 = fig.add_subplot(gs[0, 0])
sort_idx_time = np.argsort(times_min)  # Sort by time (fastest to slowest)
bars = ax1.bar(range(len(policies)), times_min[sort_idx_time], 
               color=colors_base[sort_idx_time], edgecolor='black', linewidth=1.5)
ax1.set_ylabel('Time to 100% SoC (minutes)', fontsize=11, fontweight='bold')
ax1.set_title('Charging Time Comparison', fontsize=12, fontweight='bold')
ax1.set_xticks(range(len(policies)))
ax1.set_xticklabels([policies[i].replace('_', '\n') for i in sort_idx_time], fontsize=9)
ax1.grid(axis='y', alpha=0.3)

# Add value labels on bars
for bar, time in zip(bars, times_min[sort_idx_time]):
    height = bar.get_height()
    ax1.text(bar.get_x() + bar.get_width()/2., height,
             f'{height:.1f}', ha='center', va='bottom', fontsize=9, fontweight='bold')

# ========================
# PANEL 2: Peak Temperature Comparison
# ========================
ax2 = fig.add_subplot(gs[0, 1])
sort_idx_temp = np.argsort(peak_temps)  # Sort by temperature
# Color by temperature: Green (cool) to Red (hot)
norm = plt.Normalize(vmin=peak_temps.min(), vmax=peak_temps.max())
cmap = plt.cm.RdYlGn_r  # Red (hot) to Green (cool)
colors_temp = cmap(norm(peak_temps[sort_idx_temp]))

bars = ax2.bar(range(len(policies)), peak_temps[sort_idx_temp],
               color=colors_temp, edgecolor='black', linewidth=1.5)
ax2.axhline(y=333, color='red', linestyle='--', linewidth=2.5, label='60°C Safety Limit', alpha=0.7)
ax2.set_ylabel('Peak Temperature (K)', fontsize=11, fontweight='bold')
ax2.set_title('Thermal Stress Comparison', fontsize=12, fontweight='bold')
ax2.set_xticks(range(len(policies)))
ax2.set_xticklabels([policies[i].replace('_', '\n') for i in sort_idx_temp], fontsize=9)
ax2.legend(loc='upper left', fontsize=9)
ax2.grid(axis='y', alpha=0.3)

# Add value labels on bars
for bar, temp in zip(bars, peak_temps[sort_idx_temp]):
    height = bar.get_height()
    ax2.text(bar.get_x() + bar.get_width()/2., height,
             f'{height:.1f}', ha='center', va='bottom', fontsize=9, fontweight='bold')

# ========================
# PANEL 3: Current & SOC Dynamics
# ========================
ax3 = fig.add_subplot(gs[1, 0])

# Plot all policies' current profiles
for policy_name, df in policy_data.items():
    policy_idx = np.where(policies == policy_name)[0][0]
    ax3.plot(df['time'] / 60, df['current'], label=policy_name, 
             color=colors_base[policy_idx], linewidth=2.5, alpha=0.8)

ax3.set_xlabel('Time (minutes)', fontsize=11, fontweight='bold')
ax3.set_ylabel('Current (A)', fontsize=11, fontweight='bold')
ax3.set_title('Current Profile Dynamics', fontsize=12, fontweight='bold')
ax3.tick_params(axis='y', labelcolor='black')
ax3.grid(alpha=0.3)
ax3.legend(loc='upper right', fontsize=8, ncol=1)

# ========================
# PANEL 4: SEI Growth (Degradation)
# ========================
ax4 = fig.add_subplot(gs[1, 1])
sort_idx_sei = np.argsort(sei_growth)  # Sort by degradation (best to worst)
bars = ax4.bar(range(len(policies)), sei_growth[sort_idx_sei] * 1e10,  # Scale for visibility
               color=colors_base[sort_idx_sei], edgecolor='black', linewidth=1.5)
ax4.set_ylabel('SEI Growth (×10⁻¹⁰)', fontsize=11, fontweight='bold')
ax4.set_title('Degradation - SEI Accumulation (10 cycles)', fontsize=12, fontweight='bold')
ax4.set_xticks(range(len(policies)))
ax4.set_xticklabels([policies[i].replace('_', '\n') for i in sort_idx_sei], fontsize=9)
ax4.grid(axis='y', alpha=0.3)

# Add value labels on bars
for bar, sei in zip(bars, sei_growth[sort_idx_sei]):
    height = bar.get_height()
    ax4.text(bar.get_x() + bar.get_width()/2., height,
             f'{height:.2f}', ha='center', va='bottom', fontsize=9, fontweight='bold')

# ========================
# Overall Title
# ========================
fig.suptitle('Battery Charging Policy Comparison: Fair Analysis\n' + 
             '3 Ah battery, 20A max current, CV=4.0V (CV/CVPulse), CV=3.5V (CCCV/CCCVPulse), 10 cycles',
             fontsize=14, fontweight='bold', y=0.98)

# Save figure
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
filename = f"{LOG_DIR}/comparison_policies_optimized_{timestamp}.png"
plt.tight_layout(rect=[0, 0.03, 1, 0.96])
plt.savefig(filename, dpi=300, bbox_inches='tight')
print(f"\n✓ Optimized comparison plot saved → {filename}")

# ========================
# RANKING ANALYSIS
# ========================
print("\n" + "="*70)
print("POLICY RANKING ANALYSIS")
print("="*70)

# Normalize metrics for comparison (lower is better for all)
metrics_df_norm = metrics_df.copy()
for col in ['Charging_Time_Hours', 'Peak_Temp_K', 'Avg_Temp_K', 'SEI_Growth']:
    metrics_df_norm[col] = (metrics_df_norm[col] - metrics_df_norm[col].min()) / \
                            (metrics_df_norm[col].max() - metrics_df_norm[col].min() + 1e-10)

# Calculate overall score (weighted combination)
weights = {
    'Charging_Time_Hours': 0.3,  # Speed matters
    'Peak_Temp_K': 0.2,           # Peak temp affects safety
    'Avg_Temp_K': 0.2,            # Average temp affects degradation
    'SEI_Growth': 0.3              # SEI growth affects longevity
}

metrics_df_norm['Overall_Score'] = sum(
    weights.get(col, 0) * metrics_df_norm[col] 
    for col in metrics_df_norm.columns 
    if col in weights
)

# Sort by overall score
rankings = metrics_df_norm[['Policy', 'Overall_Score']].sort_values('Overall_Score')
rankings['Rank'] = range(1, len(rankings) + 1)

print("\nOverall Rankings (lower score = better):")
print(rankings[['Rank', 'Policy', 'Overall_Score']].to_string(index=False))

print("\nKey Findings:")
best_policy = rankings.iloc[0]['Policy']
print(f"  • Best overall policy: {best_policy}")
print(f"  • Fastest charging: {metrics_df.loc[metrics_df['Charging_Time_Hours'].idxmin(), 'Policy']}")
print(f"  • Coolest operation: {metrics_df.loc[metrics_df['Peak_Temp_K'].idxmin(), 'Policy']}")
print(f"  • Least SEI growth: {metrics_df.loc[metrics_df['SEI_Growth'].idxmin(), 'Policy']}")

plt.show()
